### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jiep** [assap-org/assap#42]

**Comment by jiep** [comment]
# Dependencias actualizadas:

* "@fortawesome/fontawesome-svg-core": "^1.2.25"
* "@fortawesome/free-solid-svg-icons": "^5.11.2"
* "@fortawesome/vue-fontawesome": "^0.1.8"
* "@tensorflow/tfjs-core": "^1.2.9"
* "@tensorflow/tfjs-node": "^1.3.2"
* "@vue/cli-plugin-babel": "^4.0.5"
* "@vue/cli-plugin-eslint": "^4.0.5"
* "@vue/cli-service": "^4.0.5"
* "babel-eslint": "^10.0.3"
* "electron": "^7.1.2"
* "eslint": "^6.6.0"
* "node-sass": "^4.13.0"
* "sass-loader": "^8.0.0"
* "vue-cli-plugin-electron-builder": "^1.4.2"
* "vue-template-compiler": "^2.6.10",
* "webpack": "^4.41.2"

# Actualización a Electron 7

```js

protocol.registerSchemesAsPrivileged([{
   scheme: 'vector',
   privileges: {
       standard: true,
       secure: true,
       supportFetchAPI: true,
   },
}]);

win = new BrowserWindow({
   width: 266,
   height: 150,
   frame: false,
   x: width - 300,
   y: 150,
   alwaysOnTop: true,
   resizable: true,
   webPreferences: {
     nodeIntegration: true,
     webSecurity: false
   }
 })

```

# Actualización @vue/cli-plugin-babel

> Sustituir babel.conf.js con

```
module.exports = {
 presets: [[
   '@vue/app',
   { useBuiltIns: "entry" }
 ]]
}
```

# Actualizado vue-template-compiler a versión ^2.6.10, eslint-plugin-vue a ^6.0.1 y añadido eslint versión ^6.6.0

**Comment by jorcuad** [comment]
The issue has been resolved.
